# Generated by Django 2.0.4 on 2018-06-20 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0002_auto_20180619_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
