# Generated by Django 2.0.4 on 2018-05-22 20:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0002_gift_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='created_at',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
