# Generated by Django 2.0.4 on 2018-06-26 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0003_gift_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
