# Generated by Django 2.0.4 on 2018-06-12 20:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0004_auto_20180529_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=-1.0, size=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.FileField(blank=True, upload_to='avatars/'),
        ),
    ]
