# Generated by Django 2.0.4 on 2018-06-12 20:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0005_auto_20180612_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None),
        ),
    ]
